//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStore.Models.CarEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTable
    {
        public int Id { get; set; }
        public string CarUniqueCode { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string ProducingCountry { get; set; }
    }
}
